name: Test with different .NET
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [6.x, 7.x, 8.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.configuration }}
      - name: Run tests
        run: dotnet test OperationalTransformation.Test/OperationalTransformation.Test.csproj
