name: Build, test and publish arifacts
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Build project
        run: dotnet build OperationalTransformation/OperationalTransformation.csproj --configuration ${{ matrix.configuration }}
      - name: Run tests
        run: dotnet test OperationalTransformation.Test/OperationalTransformation.Test.csproj --configuration ${{ matrix.configuration }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: OperationalTransformation/bin/${{ matrix.configuration }}/net8.0
